//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WOMU.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Web;
    public partial class Cart
    {
        public int CartID { get; set; }
        public int ArtikelID { get; set; }
        public int Count { get; set; }
        public System.DateTime DateCreated { get; set; }

        public const string CartSessionKey = "CartId";

        private DBTEntities1 db = new DBTEntities1();

        public static Cart GetCart(HttpContextBase context)
        {
            var cart = new Cart();
            cart.CartID = cart.getCartId(context);
            return cart;
        }

        public void RemoveFromCart(int id)
        {
            var cartItem = db.Cart.Single(
                cart => cart.CartID == CartID && cart.CartID == id);

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                }
                else
                {
                    ObjectContext oc = ((IObjectContextAdapter)cartItem).ObjectContext;

                    oc.DeleteObject(cartItem);
                }
                db.SaveChanges();
            }
        }

        public int getCartId(HttpContextBase context)
        {
            Guid tempCartId = Guid.NewGuid();
            context.Session[CartSessionKey] = tempCartId.ToString();

            return (int)context.Session[CartSessionKey];
        }
    
        public virtual Artikel Artikel { get; set; }
    }
}
