//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WOMU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTEntities : DbContext
    {
        public DBTEntities()
            : base("name=DBTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikel> Artikels { get; set; }
        public virtual DbSet<Kund> Kunds { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Orderrad> Orderrads { get; set; }
        public virtual DbSet<PostNrOrt> PostNrOrts { get; set; }
    }
}
