//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WOMU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTEntities1 : DbContext
    {
        public DBTEntities1()
            : base("name=DBTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikel> Artikel { get; set; }
        public virtual DbSet<Kund> Kund { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orderrad> Orderrad { get; set; }
    }
}
